Task/86 markdown description
GAIA-X4PLC-AAD/portal pull request #104
Opened 2024-09-26 09:06 UTC by zsoltker

2024-09-27 07:13 UTC, devbysp requested changes

2024-09-27 07:13 UTC, devbysp commented on src/components/detailsPage/pages/resources/ResourcesDetailsPage.tsx
> +        console.error('Error fetching self descriptions:', error);
The error is already logged inside the `cypherQuery` you do not needed to do it again.

2024-09-27 07:13 UTC, devbysp commented on src/components/detailsPage/pages/resources/ResourcesMainContent.tsx
> +export default function ResourcesMainContent({ cardData }: Readonly<IDetailsCardProps>) {
The name should be in singular `ResourceMainContent`. You just show the content of a single resource.

2024-09-27 07:13 UTC, devbysp commented on src/components/detailsPage/pages/resources/ResourcesDetailsPage.tsx
> +export default function ResourcesDetailsPage() {
The name should be in singular `ResourceDetailsPage`. You just show the details of a single resource.

2024-09-30 15:17 UTC, devbysp commented on src/common/markdown/GMarkdown.tsx
> +const GMarkdown: React.FC<GMarkdownProps> = ({ isCard, maxContentHeight = 200, children }) => {
This is not solved.

2024-09-30 15:28 UTC, devbysp requested changes

2024-09-30 15:28 UTC, devbysp commented on src/common/markdown/Markdown.tsx
> +type GMarkdownProps = {
Can you please rename the `GMarkdownProps` too.

2024-10-01 10:49 UTC, devbysp approved these changes

2024-10-07 16:38 UTC, Huber-David approved these changes

2024-10-08 05:28 UTC, merged